Add missing library dependencies in 'build.conf', following some recent change that made some more libsvn_client functions depend on libsvn_wc. (The error was, "undefined reference to `svn_wc__node_is_status_deleted'".)
* build.conf
  (client-test, svnmucc): Add libsvn_wc to the 'libs' line.


git-svn-id: http://svn.apache.org/repos/asf/subversion/trunk@901778 13f79535-47bb-0310-9956-ffa450edef68