First step towards using a specialized list type for ra_svn items.
This introduces svn_ra_svn__list_t as a mere alias to apr_array_header_t
and replaces all uses of the latter where they contain svn_ra_svn__item_t.
Exception: the command function definition because that one will require
a specific conversion routine.  So, lots of code churn here but no
intended functional change.

After a few more of these formal mirgration steps, we will make the new
list type type-safe and more light-weight than the generic APR array.

* subversion/include/private/svn_ra_svn_private.h
  (svn_ra_svn__list_t): Define our new list type.
  (svn_ra_svn__item_t,
   svn_ra_svn__to_public_array,
   svn_ra_svn__to_private_array,
   svn_ra_svn__set_capabilities,
   svn_ra_svn__parse_tuple,
   svn_ra_svn__parse_proplist,
   svn_ra_svn__read_data_log_changed_entry)
   svn_ra_svn__to_public_item): Switch to the new list type for
                                protocol items.

* subversion/libsvn_ra_svn/ra_svn.h
  (svn_ra_svn__handle_failure_status,
   svn_ra_svn__do_cyrus_auth,
   svn_ra_svn__do_internal_auth,
   svn_ra_svn__find_mech): Same.

* subversion/libsvn_ra_svn/client.c
  (make_connection,
   parse_prop_diffs,
   handle_auth_request,
   open_session,
   ra_svn_rev_proplist,
   parse_iproplist,
   ra_svn_get_file,
   ra_svn_get_dir,
   perform_ra_svn_log, 
   ra_svn_stat,
   ra_svn_lock_compat,
   ra_svn_lock,
   ra_svn_unlock,
   ra_svn_get_lock,
   ra_svn_get_locks,
   ra_svn_replay_range,
   ra_svn_get_inherited_props): Same.

* subversion/libsvn_ra_svn/cyrus_auth.c
  (svn_ra_svn__do_cyrus_auth): Same.

* subversion/libsvn_ra_svn/editorp.c
  (ra_svn_handle_target_rev,
   ra_svn_handle_open_root,
   ra_svn_handle_delete_entry,
   ra_svn_handle_add_dir,
   ra_svn_handle_open_dir,
   ra_svn_handle_change_dir_prop,
   ra_svn_handle_close_dir,
   ra_svn_handle_absent_dir,
   ra_svn_handle_add_file,
   ra_svn_handle_open_file,
   ra_svn_handle_apply_textdelta,
   ra_svn_handle_textdelta_chunk,
   ra_svn_handle_textdelta_end,
   ra_svn_handle_change_file_prop,
   ra_svn_handle_close_file,
   ra_svn_handle_absent_file,
   ra_svn_handle_close_edit,
   ra_svn_handle_abort_edit,
   ra_svn_handle_finish_replay,
   blocked_write,
   svn_ra_svn_drive_editor2): Same.

* subversion/libsvn_ra_svn/internal_auth.c
  (svn_ra_svn__find_mech,
   svn_ra_svn__do_internal_auth): Same.

* subversion/libsvn_ra_svn/marshal.c
  (svn_ra_svn__to_public_array,
   svn_ra_svn__to_private_array,
   svn_ra_svn_set_capabilities,
   svn_ra_svn__set_capabilities,
   vparse_tuple,
   svn_ra_svn__parse_tuple,
   svn_ra_svn__parse_proplist,
   svn_ra_svn__handle_failure_status,
   svn_ra_svn__read_cmd_response,
   svn_ra_svn__handle_command,
   svn_ra_svn__read_string,
   svn_ra_svn__read_cstring,
   svn_ra_svn__read_word,
   svn_ra_svn__read_revision,
   svn_ra_svn__read_boolean,
   svn_ra_svn__read_list,
   svn_ra_svn__read_check_array_size,
   svn_ra_svn__read_data_log_changed_entry): Same.

* subversion/svnserve/serve.c
  (set_path,
   delete_path,
   link_path,
   finish_report,
   abort_report,
   reparent,
   get_latest_rev,
   do_change_rev_prop,
   change_rev_prop2,
   change_rev_prop,
   rev_proplist,
   rev_prop,
   add_lock_tokens,
   unlock_paths,
   commit,
   get_file,
   get_dir, 
   update,
   switch_cmd,
   status,
   diff,
   get_mergeinfo,
   log_cmd,
   check_path,
   stat_cmd,
   get_locations, 
   get_location_segments,
   get_file_revs,
   lock, 
   lock_many, 
   unlock, 
   unlock_many, 
   get_lock,
   get_locks,
   replay,
   replay_range, 
   get_deleted_rev,
   get_inherited_props,
   construct_server_baton): Same.

* subversion/libsvn_ra_svn/deprecated.c
  (svn_ra_svn_parse_tuple,
   svn_ra_svn_parse_proplist): Same. A temporary variable is used to
                               prevent future type conflicts.


git-svn-id: http://svn.apache.org/repos/asf/subversion/trunk@1700831 13f79535-47bb-0310-9956-ffa450edef68